package principal;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;

public class frameJuego extends javax.swing.JFrame {
    public frameJuego() {
        initComponents();
    }
    
    //Estas son las funciones que se usan para recibir datos.
    public void setJugadoresArena(ArrayList<Personaje> personajes){
        arena.setPersonajes(personajes);
    }
    
    public void setEquipos(ArrayList<Equipo> equipos){
        this.equipos = equipos;
    }
    
    public void setPersonajes(ArrayList<Personaje> personajes){
        this.personajes = personajes;
    }
    
    //Declaración de areas
    Area arena = new Area("Arena");
    Area bosque = new Area("Bosque");
    Area costa = new Area("Costa");
    
    //Declaración de variables
    int dia = 1;
    boolean sumar = false;
    boolean finalizado = false;
    
    ArrayList<Area> areas = new ArrayList<>();
    DefaultListModel muertos = new DefaultListModel();
    ArrayList<Equipo> equipos = new ArrayList<>();
    ArrayList<Personaje> personajes = new ArrayList<>();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        mapa = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jugadoresArea = new javax.swing.JList<>();
        conexiones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFallecidos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        displayMuerte = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaEventos = new javax.swing.JTextArea();
        pasarDia = new javax.swing.JButton();
        labelDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mapa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Arena", "Bosque", "Costa" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mapa);

        jugadoresArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jugadoresArea);

        conexiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conexiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexionesActionPerformed(evt);
            }
        });

        listaFallecidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listaFallecidos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Fallecidos:");

        displayMuerte.setEditable(false);
        displayMuerte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        areaEventos.setEditable(false);
        areaEventos.setColumns(20);
        areaEventos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaEventos.setRows(5);
        areaEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(areaEventos);

        pasarDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pasarDia.setText("Pasar día");
        pasarDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasarDiaMouseClicked(evt);
            }
        });

        labelDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDia.setText("Inicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conexiones)
                    .addComponent(jScrollPane3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayMuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pasarDia)
                .addGap(629, 629, 629))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3))
                                .addGap(32, 32, 32)
                                .addComponent(conexiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(displayMuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pasarDia)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conexionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conexionesActionPerformed

    private void mapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaMouseClicked
        String selected = mapa.getSelectedValue();
        
        switch(selected){
            case "Arena" ->{
                String texto = "Conecta con:" + arena.getStringConexiones();
                conexiones.setText(texto);
                jugadoresArea.setModel(arena.devolverModeloJugadores());
            }
            case "Bosque" ->{
                String texto = "Conecta con:" + bosque.getStringConexiones();
                conexiones.setText(texto);
                jugadoresArea.setModel(bosque.devolverModeloJugadores());
            }
            case "Costa" ->{
                String texto = "Conecta con:" + costa.getStringConexiones();
                conexiones.setText(texto);
                jugadoresArea.setModel(costa.devolverModeloJugadores());
            }
        }
    }//GEN-LAST:event_mapaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void pasarDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasarDiaMouseClicked
        accionFalse();
        if(finalizado){
        	//Esto evita que la simulación prosiga con un único jugador.
            JOptionPane.showMessageDialog(rootPane, "La simulación ha finalizado");
        }else{
            areaEventos.setText("");
            /*
             * Primero, se comprueba que no se haya producido una condicion de victoria.
             * Después, si es necesario se pasa el dia, se actualiza el display de este, y se realizan los eventos.
             */
            if(!checkVictoria()){
                if(sumar){
                    dia++;
                    labelDia.setText(String.format("Dia %d", dia));
                    sumar = false;
                    ticDiurno();
                }else{
                    sumar = true;
                    labelDia.setText(String.format("Noche %d", dia));
                    ticNocturno();
                }
            }else{
                victoria();
            }
        }
    }//GEN-LAST:event_pasarDiaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Acciones que se realizan al abrir la ventana.
    	areas.add(arena);
        areas.add(bosque);
        areas.add(costa);
        
        arena.añadirConexion(bosque);
        arena.añadirConexion(costa);
        bosque.añadirConexion(arena);
        costa.añadirConexion(arena);
        
        asignarEventos();
        
        //Esto hace que si se inicia con un solo jugador, este gane automaticamente,
        if(checkVictoria()){
            victoria();
        }else{
            ticInicial();
        }
        listaFallecidos.setModel(muertos);
    }//GEN-LAST:event_formWindowOpened

    
    private void ticDiurno(){
        String textoFinal = "";
        for (Area area : areas) {
            textoFinal += area.realizarEventos('D');
            for (Object muerto : area.darMuertos()) {
                muertos.addElement(muerto);
                area.limpiarMuertos();
            }
        }
        areaEventos.setText(textoFinal);
    }
    
    private void ticNocturno(){
        String textoFinal = "";
        for (Area area : areas) {
            textoFinal += area.realizarEventos('N');
            for (Object muerto : area.darMuertos()) {
                muertos.addElement(muerto);
                area.limpiarMuertos();
            }
        }
        areaEventos.setText(textoFinal);
    }
    
    private void ticInicial(){
        String textoFinal = "";
        for (Area area : areas) {
            textoFinal += area.realizarEventos('I');
            for (Object muerto : area.darMuertos()) {
                muertos.addElement(muerto);
                area.limpiarMuertos();
            }
        }
        areaEventos.setText(textoFinal);
    }
    
    private boolean checkVictoria(){
    	//Si detecta uno o menos jugadores, declara una victoria.
        int totalJug = 0;
        for (Area area : areas) {
            for (Personaje pers : area.jugadores) {
                totalJug++;
            }
        }
        if(totalJug > 1){
            return false;
        }else{
            return true;
        }
    }
    
    private Personaje getGanador(){
        for (Area area : areas) {
            if(!area.jugadores.isEmpty()) return area.jugadores.get(0);
        }
        return new Personaje();
    }
    
    private String getEquipo(Personaje personaje){
        String devolver = "";
        for (Equipo equipo : equipos) {
            if(equipo.getMiembros().contains(personaje)) devolver = equipo.nombre;
        }
        return devolver;
    }
    
    private void victoria(){
        Personaje ganador = getGanador();
        String equipo = getEquipo(ganador);
        String ganadorText = String.format("¡%s del equipo %s es el ganador!", ganador.nombre, equipo);
        areaEventos.setText(ganadorText);
        finalizado = true;
    }
    
    private void accionFalse(){
        for (Area area : areas) {
            for (Personaje personaje : area.jugadores){
                personaje.setAccion(false);
            }
        }
    }
    //Declaracion de eventos
    private void asignarEventos(){
    	//Esta funcion, pues... asigna eventos.
        arena.añadirEvento(new Evento('I', 1, false, "%s escapa de la arena inicial."));
        arena.añadirEvento(new Evento('I', 1, false, "%s busca, sin éxito, suministros en la arena inicial."));
        arena.añadirEvento(new Evento('I', 2, true, "%s es apuñalado por %s por la espalda."));
        arena.añadirEvento(new Evento('I', 2, false, "%s y %s hacen una pequeña tregua para escapar de la arena inicial juntos."));
        arena.añadirEvento(new Evento('I', 3, false, "%s, %s y %s se ignoran mutuamente para beneficio de todos."));
        arena.añadirEvento(new Evento('I',1,false,"%s se tropieza intentando huir de la arena incial."));
        arena.añadirEvento(new Evento('I',1,false,"%s busca y encuentra suministros en la arena inicial."));
        arena.añadirEvento(new Evento('I',1,false,"%s encuentra un pequeño cuchillo en la arena inicial."));
        arena.añadirEvento(new Evento('I',1,false,"%s encuentra armamento en la arena inicial."));
        arena.añadirEvento(new Evento('I',2,false,"%s intenta huir, mientras que %s le persigue."));
        arena.añadirEvento(new Evento('I',2,false,"%s huye de la arena, sin saber que %s lo está persiguiendo."));
        arena.añadirEvento(new Evento('I',3,false,"%s, %s y %s se meten en una pelea, sin embargo, se dan cuenta de que no es el mejor momento y se separan."));
        arena.añadirEvento(new Evento('I', 2, true, "%s come una manzana que le da %s, sin saber que estaba envenada con cianuro."));
        arena.añadirEvento(new Evento('I',1,false,"%s agarra una pala."));
        arena.añadirEvento(new Evento('I',1,false,"%s agarra una mochila y se va."));
        arena.añadirEvento(new Evento('I',2,false,"%s y %s se pelean por una mochila de suministros, sin darse cuenta de que está vacia."));
        arena.añadirEvento(new Evento('I',2,false,"%s y %s se pelean por una mochila de suministros."));
        arena.añadirEvento(new Evento('I',1,false,"%s encuentra una cantimplora."));
        arena.añadirEvento(new Evento('I',1,false,"%s pilla toda la comida que puede."));
        arena.añadirEvento(new Evento('I',2,false,"%s le rompe la nariz a %s por un poco de comida."));
        arena.añadirEvento(new Evento('I',1,false,"%s grita por ayuda."));
        arena.añadirEvento(new Evento('I', 1, true, "%s agarra una mochila, sin darse cuenta de que era una trampa bomba, y explota en mil pedazos."));
        arena.añadirEvento(new Evento('D', 1, false, "%s patrulla la arena inicial."));
        arena.añadirEvento(new Evento('D', 1, false, "%s busca algo util entre lo que queda tras el saqueo inicial."));
        arena.añadirEvento(new Evento('D', 1, false, "%s encuentra comida en buen estado que nadie recogió durante el saqueo inicial."));
        arena.añadirEvento(new Evento('D', 2, false, "%s se encuentra por sorpresa a %s, pero se separan rapidamente."));
        arena.añadirEvento(new Evento('D', 2, true, "%s pensaba que ya no quedaba nadie en la arena inicial, pero %s le demuestra que se equivoca con un par de puñaladas."));
        arena.añadirEvento(new Evento('D', 1, false, "%s encuentra una sarten."));
        arena.añadirEvento(new Evento('D', 1, false, "%s no tiene suerte buscando restos del saqueo inicial."));
        arena.añadirEvento(new Evento('N', 1, false, "%s decide pasar la noche en la arena inicial."));
        arena.añadirEvento(new Evento('N', 1, false, "%s pasa la noche en vela vigilando la arena inicial."));
        arena.añadirEvento(new Evento('N', 3, false, "%s, %s y %s se encuentran en la arena inicial, pero todos deciden que están demasiado cansados para pelear."));
        arena.añadirEvento(new Evento('N', 1, false, "%s duerme en el centro de la arena inicial, con la esperanza de que nadie le vea."));
        arena.añadirEvento(new Evento('N', 1, false, "A %s le hubiera gustado pasar la noche fuera de la arena inicial, pero no le dio tiempo a escapar."));
        arena.añadirEvento(new Evento('N', 1, false, "%s se queda dormido mirando los aviones que pasan por encima de la arena inicial."));
        arena.añadirEvento(new Evento('N', 1, false, "%s se pasa toda la noche intentando emboscar a una linterna que vio en la distancia, sin darse cuenta de que era una farola."));
        arena.añadirEvento(new Evento('D', 2, true, "%s es golpeado en la cabeza con una sarten por %s"));
        arena.añadirEvento(new Evento('D', 1, false, "%s se encuentra una sarten que alguine había tirado."));
        arena.añadirEvento(new Evento('D', 1, false, "%s tira una sarten que tenía por algún motivo."));
        arena.añadirEvento(new Evento('N', 1, false, "%s duerme en el cemento de la arena inicial."));
        arena.añadirEvento(new Evento('N', 1, true, "%s intenta subirse a una farola para ver mejor, pero se cae y muere."));
        
        bosque.añadirEvento(new Evento('D', 1, false, "%s busca suministros en el bosque."));
        bosque.añadirEvento(new Evento('D', 1, false, "%s recoge frutos del bosque."));
        bosque.añadirEvento(new Evento('N', 1, false, "%s duerme en una cueva."));
        bosque.añadirEvento(new Evento('N', 1, false, "%s sube a un arbol para dormir."));
        bosque.añadirEvento(new Evento('D',1,false,"%s recoje musgo."));
        bosque.añadirEvento(new Evento('D',1,false,"%s caza conejos."));
        bosque.añadirEvento(new Evento('D',1,false,"%s se cae a un río."));
        bosque.añadirEvento(new Evento('D',2,false,"%s es atacado por un oso, pero %s le ayuda a huir."));
        bosque.añadirEvento(new Evento('N', 2, false, "%s le roba las cosas a %s mientras duerme."));
        bosque.añadirEvento(new Evento('D', 1, false, "%s se va de caza."));
        bosque.añadirEvento(new Evento('D',1,false,"%s descubre una cueva."));
        bosque.añadirEvento(new Evento('D', 1, true, "%s muere arroyado por un jabalí."));
        bosque.añadirEvento(new Evento('N', 2, false, "%s deja a %s entrar en su tienda de campaña."));
        
        costa.añadirEvento(new Evento('D', 1, false, "%s se baña en el mar."));
        costa.añadirEvento(new Evento('D', 2, true, "%s cae en la trampa de confiar en %s, y muere ahogado."));
        costa.añadirEvento(new Evento('N', 1, false, "%s hace una hoguera con corteza de palmera."));
        costa.añadirEvento(new Evento('N', 1, false, "%s mira las estrellas mientras escucha el oleaje."));
        costa.añadirEvento(new Evento('D', 1, false, "%s da un paseo por la playa."));
        costa.añadirEvento(new Evento('D', 1, false, "%s se lava las heridas con agua de mar."));
        costa.añadirEvento(new Evento('D', 1, false, "%s hierve agua para obtener agua potable."));
        costa.añadirEvento(new Evento('D', 2, false, "%s construye un castillo de arena para distraerse de los horrores del capitalismo."));
        costa.añadirEvento(new Evento('D',1,false,"%s pesca."));
        costa.añadirEvento(new Evento('N', 2, false, "%s y %s hacen una tregua y hablan sobre las personas que quedan con vida."));
        costa.añadirEvento(new Evento('D', 1, true, "%s pisa un pez roca y muere."));
        
        //Eventos universales
        arena.añadirEvento(new Evento('U', 2, false, "%s le ruega a %s que le mate, pero este se niega."));
        bosque.añadirEvento(new Evento('U', 2, false, "%s le ruega a %s que le mate, pero este se niega."));
        costa.añadirEvento(new Evento('U', 2, false, "%s le ruega a %s que le mate, pero este se niega."));
        
        arena.añadirEvento(new Evento('U', 2, true, "%s le ruega a %s que le mate, y este acepta."));
        bosque.añadirEvento(new Evento('U', 2, true, "%s le ruega a %s que le mate, y este acepta."));
        costa.añadirEvento(new Evento('U', 2, true, "%s le ruega a %s que le mate, y este acepta."));
    }
	
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEventos;
    private javax.swing.JTextField conexiones;
    private javax.swing.JTextField displayMuerte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> jugadoresArea;
    private javax.swing.JLabel labelDia;
    private javax.swing.JList<String> listaFallecidos;
    private javax.swing.JList<String> mapa;
    private javax.swing.JButton pasarDia;
    // End of variables declaration//GEN-END:variables
}
